import React from "react"

import "@/styles/globals.css"
import { type Metadata } from "next"
import { ClerkProvider } from "@clerk/nextjs"
import { Toaster } from "react-hot-toast"

import { fontSans } from "@/lib/fonts"
import { cn } from "@/lib/utils"
import { MouseTracker } from "@/components/mouse-tracker"
import { SiteHeader } from "@/components/site-header"
import { TailwindIndicator } from "@/components/tailwind-indicator"
import { ThemeProvider } from "@/components/theme-provider"

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body
          className={cn(
            "min-h-screen bg-background font-sans antialiased",
            fontSans.variable
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative flex min-h-screen flex-col">
              <SiteHeader />
              <MouseTracker />
              <main>{children}</main>
            </div>
            <TailwindIndicator />
          </ThemeProvider>
          <Toaster position="top-right" />
        </body>
      </html>
    </ClerkProvider>
  )
}
